DROP TABLE IF EXISTS USERS_ROLES;
DROP TABLE IF EXISTS ROLES_PRIVILEGES;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS ROLE;
DROP TABLE IF EXISTS PRIVILEGE;


DROP TABLE IF EXISTS CONSTANT_PARAMETERS;
DROP TABLE IF EXISTS MUTABLE_PARAMETERS;
DROP TABLE IF EXISTS RESULTS;
DROP TABLE IF EXISTS SHP_GEOMETRY;
DROP TABLE IF EXISTS DBF_DATA;


CREATE TABLE IF NOT EXISTS PRIVILEGE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS ROLE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS USERS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(255),
    PASSWORD VARCHAR(255),
    EMAIL VARCHAR(255),
    ENABLED BOOLEAN
);

CREATE TABLE IF NOT EXISTS ROLES_PRIVILEGES (
    ROLE_ID INT,
    PRIVILEGE_ID INT,
    FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID),
    FOREIGN KEY (PRIVILEGE_ID) REFERENCES PRIVILEGE(ID),
    PRIMARY KEY (ROLE_ID, PRIVILEGE_ID)
);

CREATE TABLE IF NOT EXISTS USERS_ROLES (
    USER_ID INT,
    ROLE_ID INT,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID),
    PRIMARY KEY (USER_ID, ROLE_ID)
);


CREATE TABLE IF NOT EXISTS DBF_DATA (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FILE_ID INT,
    FILE_NAME VARCHAR(255),
    FILE_UNIQUE_ID INT,
    IDENTIFIER INT,
    SPEED_1 INT,
    SPEED_2 INT,
    SPEED_3 INT,
    ACOUSTIC_CAT_DAY_1 INT,
    ACOUSTIC_CAT_DAY_2 INT,
    ACOUSTIC_CAT_DAY_3 INT,
    ACOUSTIC_CAT_NIGHT_1 INT,
    ACOUSTIC_CAT_NIGHT_2 INT,
    ACOUSTIC_CAT_NIGHT_3 INT,
    IDENTIFIER_R INT,
    SPEED_1_R INT,
    SPEED_2_R INT,
    SPEED_3_R INT,
    ACOUSTIC_CAT_DAY_1_R INT,
    ACOUSTIC_CAT_DAY_2_R INT,
    ACOUSTIC_CAT_DAY_3_R INT,
    ACOUSTIC_CAT_NIGHT_1_R INT,
    ACOUSTIC_CAT_NIGHT_2_R INT,
    ACOUSTIC_CAT_NIGHT_3_R INT
);

CREATE TABLE IF NOT EXISTS CONSTANT_PARAMETERS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    A1_CATEGORY_I DOUBLE,
    A1_CATEGORY_II DOUBLE,
    A1_CATEGORY_III DOUBLE,
    B1_CATEGORY_I DOUBLE,
    B1_CATEGORY_II DOUBLE,
    B1_CATEGORY_III DOUBLE,
    C1_CATEGORY_I DOUBLE,
    C1_CATEGORY_II DOUBLE,
    C1_CATEGORY_III DOUBLE,
    D1_CATEGORY_I DOUBLE,
    D1_CATEGORY_II DOUBLE,
    D1_CATEGORY_III DOUBLE,
    E1_CATEGORY_I DOUBLE,
    E1_CATEGORY_II DOUBLE,
    E1_CATEGORY_III DOUBLE,
    F1_CATEGORY_I DOUBLE,
    F1_CATEGORY_II DOUBLE,
    F1_CATEGORY_III DOUBLE,
    ANGLE_OF_VIEW_DEFAULT DOUBLE,
    KD_FACTOR DOUBLE,
    REFERENCE_DISTANCE DOUBLE,
    PRESSURE_TO_INTENSITY_CONVERSION DOUBLE,
    DAY_HOURS DOUBLE,
    NIGHT_HOURS DOUBLE
);


CREATE TABLE IF NOT EXISTS MUTABLE_PARAMETERS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FILE_ID INT,
    FILE_UNIQUE_ID INT,
    LTH_DAY DOUBLE,
    LTH_NIGHT DOUBLE,
    K_ROAD_SURFACE_ROUGHNESS DOUBLE,
    KR_REFLECTION DOUBLE,
    C_SOUND_ABSORPTION_FACTOR DOUBLE,
    ANGLE_OF_VIEW DOUBLE,
    TRAFFIC_TYPE VARCHAR(255),
    SLOPE_ELEVATION DOUBLE,
    P_PARAMETER_CAT_1 DOUBLE,
    P_PARAMETER_CAT_2_3 DOUBLE
);


CREATE TABLE IF NOT EXISTS RESULTS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DBF_DATA_ID INT,
    FILE_ID INT,
    FILE_UNIQUE_ID INT,
    LAEQ_DAY DOUBLE,
    LAEQ_NIGHT DOUBLE,
    LW_DAY DOUBLE,
    LW_NIGHT DOUBLE,
    IMPACT_AREA_DAY DOUBLE,
    IMPACT_AREA_NIGHT DOUBLE,
    PROTECTIVE_DISTANCE_DAY DOUBLE,
    PROTECTIVE_DISTANCE_NIGHT DOUBLE,
    NOISE_AT_GIVEN_DISTANCE_DAY DOUBLE,
    NOISE_AT_GIVEN_DISTANCE_NIGHT DOUBLE,
    DIFFERENCE_DAY_0 DOUBLE,
    DIFFERENCE_NIGHT_0 DOUBLE,
    DIFFERENCE_DAY_1 DOUBLE,
    DIFFERENCE_NIGHT_1 DOUBLE,
    DIFFERENCE_DAY_2 DOUBLE,
    DIFFERENCE_NIGHT_2 DOUBLE,
    FOREIGN KEY (DBF_DATA_ID) REFERENCES DBF_DATA(ID)
);

CREATE TABLE IF NOT EXISTS SHP_GEOMETRY (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DBF_DATA_ID INT,
    FILE_ID INT,
    FILE_UNIQUE_ID INT,
    GEOMETRY_WKT TEXT,
    FOREIGN KEY (DBF_DATA_ID) REFERENCES DBF_DATA(ID)
);

