CREATE TABLE IF NOT EXISTS MUTABLE_PARAMETERS (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    DBF_DATA_ID INT,
	FILE_ID INT,
	FILE_UNIQUE_ID INT,
	LTH_DAY DOUBLE,
	LTH_NIGHT DOUBLE,
	K_ROAD_SURFACE_ROUGHNESS DOUBLE,
	KR_REFLECTION DOUBLE,
	C_SOUND_ABSORPTION_FACTOR DOUBLE,
	ANGLE_OF_VIEW DOUBLE,
	TRAFFIC_TYPE VARCHAR(255),
	SLOPE_ELEVATION DOUBLE,
	P_PARAMETER_CAT_1 DOUBLE,
	P_PARAMETER_CAT_2_3 DOUBLE,
    FOREIGN KEY (DBF_DATA_ID) REFERENCES DBF_DATA(ID)
);