
CREATE TABLE IF NOT EXISTS CONSTANT_PARAMETERS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    A1_CATEGORY_I DOUBLE,
    A1_CATEGORY_II DOUBLE,
    A1_CATEGORY_III DOUBLE,
    B1_CATEGORY_I DOUBLE,
    B1_CATEGORY_II DOUBLE,
    B1_CATEGORY_III DOUBLE,
    C1_CATEGORY_I DOUBLE,
    C1_CATEGORY_II DOUBLE,
    C1_CATEGORY_III DOUBLE,
    D1_CATEGORY_I DOUBLE,
    D1_CATEGORY_II DOUBLE,
    D1_CATEGORY_III DOUBLE,
    E1_CATEGORY_I DOUBLE,
    E1_CATEGORY_II DOUBLE,
    E1_CATEGORY_III DOUBLE,
    F1_CATEGORY_I DOUBLE,
    F1_CATEGORY_II DOUBLE,
    F1_CATEGORY_III DOUBLE,
    ANGLE_OF_VIEW_DEFAULT DOUBLE,
    KD_FACTOR DOUBLE,
    REFERENCE_DISTANCE DOUBLE,
    PRESSURE_TO_INTENSITY_CONVERSION DOUBLE,
    DAY_HOURS DOUBLE,
    NIGHT_HOURS DOUBLE
);

