DROP TABLE IF EXISTS USERS_ROLES;
DROP TABLE IF EXISTS ROLES_PRIVILEGES;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS ROLE;
DROP TABLE IF EXISTS PRIVILEGE;
DROP TABLE IF EXISTS CONSTANT_PARAMETERS;