
CREATE TABLE IF NOT EXISTS ROLES_PRIVILEGES (
    ROLE_ID INT,
    PRIVILEGE_ID INT,
    FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID),
    FOREIGN KEY (PRIVILEGE_ID) REFERENCES PRIVILEGE(ID),
    PRIMARY KEY (ROLE_ID, PRIVILEGE_ID)
);