
CREATE TABLE IF NOT EXISTS USERS_ROLES (
    USER_ID INT,
    ROLE_ID INT,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID),
    PRIMARY KEY (USER_ID, ROLE_ID)
);