
CREATE TABLE IF NOT EXISTS PRIVILEGE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS ROLE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255)
);
