CREATE TABLE IF NOT EXISTS SHP_GEOMETRY (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	DBF_DATA_ID INT,
	FILE_ID INT,
	FILE_UNIQUE_ID INT,
	GEOMETRY_WKT TEXT,
	FOREIGN KEY (DBF_DATA_ID) REFERENCES DBF_DATA(ID)
);